# Generated by Django 3.1 on 2020-09-05 14:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Check',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('totalsum', models.IntegerField()),
                ('orderid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='food.order')),
                ('servicefee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='food.servicepercentage')),
            ],
        ),
        migrations.CreateModel(
            name='Amount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveIntegerField()),
                ('list_of_check', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meals', to='food.check')),
                ('name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='food.meal')),
            ],
        ),
    ]
