# Generated by Django 3.1 on 2020-09-08 09:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0002_amount_check'),
    ]

    operations = [
        migrations.CreateModel(
            name='MealsToOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count_meal', models.PositiveIntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='check',
            name='orderid',
        ),
        migrations.RemoveField(
            model_name='check',
            name='servicefee',
        ),
        migrations.RemoveField(
            model_name='countofmeal',
            name='name_meal',
        ),
        migrations.RemoveField(
            model_name='countofmeal',
            name='order',
        ),
        migrations.RenameField(
            model_name='meal',
            old_name='categoryid',
            new_name='category_id',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='tableid',
            new_name='table_id',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='tablename',
            new_name='table_name',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='waiterid',
            new_name='waiter_id',
        ),
        migrations.DeleteModel(
            name='Amount',
        ),
        migrations.DeleteModel(
            name='Check',
        ),
        migrations.DeleteModel(
            name='CountOfMeal',
        ),
        migrations.AddField(
            model_name='mealstoorder',
            name='order_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meals_id', to='food.order'),
        ),
        migrations.AddField(
            model_name='meal',
            name='meals_to_order',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='food.mealstoorder'),
            preserve_default=False,
        ),
    ]
