# Generated by Django 3.1 on 2020-09-05 17:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0002_amount_check'),
    ]

    operations = [
        migrations.AddField(
            model_name='check',
            name='order',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='counts', to='food.order'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='check',
            name='orderid',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='food.order'),
        ),
        migrations.DeleteModel(
            name='Amount',
        ),
    ]
