# Generated by Django 3.1 on 2020-09-05 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0003_auto_20200905_2320'),
    ]

    operations = [
        migrations.AlterField(
            model_name='check',
            name='totalsum',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
