# Generated by Django 3.1 on 2020-09-08 14:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0003_auto_20200908_1508'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meal',
            name='meals_to_order',
        ),
        migrations.AddField(
            model_name='mealstoorder',
            name='meals_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='food.meal'),
            preserve_default=False,
        ),
    ]
