# Generated by Django 3.1 on 2020-09-08 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0004_auto_20200908_2032'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='table_name',
        ),
    ]
