# Generated by Django 3.1 on 2020-09-05 17:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0005_auto_20200905_2325'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='check',
            name='order',
        ),
        migrations.AlterField(
            model_name='check',
            name='orderid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='counts', to='food.order'),
        ),
    ]
