# Generated by Django 3.1 on 2020-09-06 05:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0006_auto_20200905_2327'),
    ]

    operations = [
        migrations.AlterField(
            model_name='check',
            name='servicefee',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='food.servicepercentage'),
            preserve_default=False,
        ),
    ]
