# Generated by Django 3.1 on 2020-09-08 16:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0006_check'),
    ]

    operations = [
        migrations.AddField(
            model_name='check',
            name='meals_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='food.mealstoorder'),
            preserve_default=False,
        ),
    ]
