# Generated by Django 3.1 on 2020-09-06 06:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0007_auto_20200906_1145'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='check',
            name='servicefee',
        ),
    ]
