# Generated by Django 3.1 on 2020-09-08 17:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0007_check_meals_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='check',
            name='meals_id',
        ),
        migrations.AlterField(
            model_name='check',
            name='order_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order', to='food.order'),
        ),
    ]
