# Generated by Django 3.1 on 2020-09-08 18:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0008_auto_20200908_2308'),
    ]

    operations = [
        migrations.RenameField(
            model_name='check',
            old_name='order_id',
            new_name='orders_id',
        ),
    ]
