# Generated by Django 3.1 on 2020-09-08 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0009_auto_20200909_0023'),
    ]

    operations = [
        migrations.RenameField(
            model_name='check',
            old_name='orders_id',
            new_name='order_id',
        ),
    ]
