# Generated by Django 3.1 on 2020-09-06 07:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0009_check_servicefee'),
    ]

    operations = [
        migrations.RenameField(
            model_name='countofmeal',
            old_name='count_meal',
            new_name='amount',
        ),
    ]
