# Generated by Django 3.1 on 2020-09-06 07:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0010_auto_20200906_1313'),
    ]

    operations = [
        migrations.AddField(
            model_name='check',
            name='mealsid',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='food.countofmeal'),
            preserve_default=False,
        ),
    ]
