# Generated by Django 3.1 on 2020-09-08 20:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0010_auto_20200909_0029'),
    ]

    operations = [
        migrations.AddField(
            model_name='check',
            name='mealtoorder',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='order', to='food.mealstoorder'),
            preserve_default=False,
        ),
    ]
