# Generated by Django 3.1 on 2020-09-07 06:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0012_auto_20200907_1202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='check',
            name='servicefee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='food.servicepercentage'),
        ),
        migrations.AlterField(
            model_name='servicepercentage',
            name='percentage',
            field=models.IntegerField(default=33),
        ),
    ]
