# Generated by Django 3.1 on 2020-09-09 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0013_auto_20200909_2126'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mealstoorder',
            old_name='meals_id',
            new_name='mealsid',
        ),
        migrations.RenameField(
            model_name='mealstoorder',
            old_name='order_id',
            new_name='orderid',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='table_id',
            new_name='tableid',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='waiter_id',
            new_name='waiterid',
        ),
    ]
